// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package com.zrz.game.protobuf;

public final class GameProtocol {
  private GameProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息代号
   * </pre>
   *
   * Protobuf enum {@code msg.MsgCode}
   */
  public enum MsgCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_ENTRY_CMD = 0;</code>
     */
    USER_ENTRY_CMD(0),
    /**
     * <code>USER_ENTRY_RESULT = 1;</code>
     */
    USER_ENTRY_RESULT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>USER_ENTRY_CMD = 0;</code>
     */
    public static final int USER_ENTRY_CMD_VALUE = 0;
    /**
     * <code>USER_ENTRY_RESULT = 1;</code>
     */
    public static final int USER_ENTRY_RESULT_VALUE = 1;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgCode forNumber(int value) {
      switch (value) {
        case 0: return USER_ENTRY_CMD;
        case 1: return USER_ENTRY_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
            @Override
            public MsgCode findValueByNumber(int number) {
              return MsgCode.forNumber(number);
            }
          };

    @Override
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }

    @Override
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zrz.game.protobuf.GameProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgCode[] VALUES = values();

    public static MsgCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:msg.MsgCode)
  }

  public interface UserEntryCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.UserEntryCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>string heroAvatar = 2;</code>
     * @return The heroAvatar.
     */
    java.lang.String getHeroAvatar();
    /**
     * <code>string heroAvatar = 2;</code>
     * @return The bytes for heroAvatar.
     */
    com.google.protobuf.ByteString
        getHeroAvatarBytes();
  }
  /**
   * <pre>
   **
   * 用户入场
   * 指令
   * </pre>
   *
   * Protobuf type {@code msg.UserEntryCmd}
   */
  public  static final class UserEntryCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.UserEntryCmd)
      UserEntryCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEntryCmd.newBuilder() to construct.
    private UserEntryCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEntryCmd() {
      heroAvatar_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEntryCmd();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEntryCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              heroAvatar_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zrz.game.protobuf.GameProtocol.UserEntryCmd.class, com.zrz.game.protobuf.GameProtocol.UserEntryCmd.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }

    public static final int HEROAVATAR_FIELD_NUMBER = 2;
    private volatile java.lang.Object heroAvatar_;
    /**
     * <code>string heroAvatar = 2;</code>
     * @return The heroAvatar.
     */
    @Override
    public java.lang.String getHeroAvatar() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heroAvatar_ = s;
        return s;
      }
    }
    /**
     * <code>string heroAvatar = 2;</code>
     * @return The bytes for heroAvatar.
     */
    @Override
    public com.google.protobuf.ByteString
        getHeroAvatarBytes() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (!getHeroAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, heroAvatar_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (!getHeroAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, heroAvatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zrz.game.protobuf.GameProtocol.UserEntryCmd)) {
        return super.equals(obj);
      }
      com.zrz.game.protobuf.GameProtocol.UserEntryCmd other = (com.zrz.game.protobuf.GameProtocol.UserEntryCmd) obj;

      if (getUserId()
          != other.getUserId()) {
        return false;
      }
      if (!getHeroAvatar()
          .equals(other.getHeroAvatar())) {
        return false;
      }
      if (!unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + HEROAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getHeroAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zrz.game.protobuf.GameProtocol.UserEntryCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * 用户入场
     * 指令
     * </pre>
     *
     * Protobuf type {@code msg.UserEntryCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.UserEntryCmd)
        com.zrz.game.protobuf.GameProtocol.UserEntryCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zrz.game.protobuf.GameProtocol.UserEntryCmd.class, com.zrz.game.protobuf.GameProtocol.UserEntryCmd.Builder.class);
      }

      // Construct using com.zrz.game.protobuf.GameProtocol.UserEntryCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        heroAvatar_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryCmd_descriptor;
      }

      @java.lang.Override
      public com.zrz.game.protobuf.GameProtocol.UserEntryCmd getDefaultInstanceForType() {
        return com.zrz.game.protobuf.GameProtocol.UserEntryCmd.getDefaultInstance();
      }

      @java.lang.Override
      public com.zrz.game.protobuf.GameProtocol.UserEntryCmd build() {
        com.zrz.game.protobuf.GameProtocol.UserEntryCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zrz.game.protobuf.GameProtocol.UserEntryCmd buildPartial() {
        com.zrz.game.protobuf.GameProtocol.UserEntryCmd result = new com.zrz.game.protobuf.GameProtocol.UserEntryCmd(this);
        result.userId_ = userId_;
        result.heroAvatar_ = heroAvatar_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zrz.game.protobuf.GameProtocol.UserEntryCmd) {
          return mergeFrom((com.zrz.game.protobuf.GameProtocol.UserEntryCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zrz.game.protobuf.GameProtocol.UserEntryCmd other) {
        if (other == com.zrz.game.protobuf.GameProtocol.UserEntryCmd.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getHeroAvatar().isEmpty()) {
          heroAvatar_ = other.heroAvatar_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zrz.game.protobuf.GameProtocol.UserEntryCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zrz.game.protobuf.GameProtocol.UserEntryCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>uint32 userId = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>uint32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {

        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object heroAvatar_ = "";
      /**
       * <code>string heroAvatar = 2;</code>
       * @return The heroAvatar.
       */
      @Override
      public java.lang.String getHeroAvatar() {
        java.lang.Object ref = heroAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heroAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @return The bytes for heroAvatar.
       */
      @Override
      public com.google.protobuf.ByteString
          getHeroAvatarBytes() {
        java.lang.Object ref = heroAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @param value The heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        heroAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeroAvatar() {

        heroAvatar_ = getDefaultInstance().getHeroAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @param value The bytes for heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        heroAvatar_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.UserEntryCmd)
    }

    // @@protoc_insertion_point(class_scope:msg.UserEntryCmd)
    private static final com.zrz.game.protobuf.GameProtocol.UserEntryCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zrz.game.protobuf.GameProtocol.UserEntryCmd();
    }

    public static com.zrz.game.protobuf.GameProtocol.UserEntryCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEntryCmd>
        PARSER = new com.google.protobuf.AbstractParser<UserEntryCmd>() {
      @java.lang.Override
      public UserEntryCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEntryCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEntryCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserEntryCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zrz.game.protobuf.GameProtocol.UserEntryCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserEntryResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.UserEntryResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>string heroAvatar = 2;</code>
     * @return The heroAvatar.
     */
    java.lang.String getHeroAvatar();
    /**
     * <code>string heroAvatar = 2;</code>
     * @return The bytes for heroAvatar.
     */
    com.google.protobuf.ByteString
        getHeroAvatarBytes();
  }
  /**
   * <pre>
   **
   * 用户入场
   * 结果
   * </pre>
   *
   * Protobuf type {@code msg.UserEntryResult}
   */
  public  static final class UserEntryResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.UserEntryResult)
      UserEntryResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEntryResult.newBuilder() to construct.
    private UserEntryResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEntryResult() {
      heroAvatar_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEntryResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEntryResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              heroAvatar_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zrz.game.protobuf.GameProtocol.UserEntryResult.class, com.zrz.game.protobuf.GameProtocol.UserEntryResult.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }

    public static final int HEROAVATAR_FIELD_NUMBER = 2;
    private volatile java.lang.Object heroAvatar_;
    /**
     * <code>string heroAvatar = 2;</code>
     * @return The heroAvatar.
     */
    @Override
    public java.lang.String getHeroAvatar() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heroAvatar_ = s;
        return s;
      }
    }
    /**
     * <code>string heroAvatar = 2;</code>
     * @return The bytes for heroAvatar.
     */
    @Override
    public com.google.protobuf.ByteString
        getHeroAvatarBytes() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (!getHeroAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, heroAvatar_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (!getHeroAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, heroAvatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zrz.game.protobuf.GameProtocol.UserEntryResult)) {
        return super.equals(obj);
      }
      com.zrz.game.protobuf.GameProtocol.UserEntryResult other = (com.zrz.game.protobuf.GameProtocol.UserEntryResult) obj;

      if (getUserId()
          != other.getUserId()) {
        return false;
      }
      if (!getHeroAvatar()
          .equals(other.getHeroAvatar())) {
        return false;
      }
      if (!unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + HEROAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getHeroAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zrz.game.protobuf.GameProtocol.UserEntryResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * 用户入场
     * 结果
     * </pre>
     *
     * Protobuf type {@code msg.UserEntryResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.UserEntryResult)
        com.zrz.game.protobuf.GameProtocol.UserEntryResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zrz.game.protobuf.GameProtocol.UserEntryResult.class, com.zrz.game.protobuf.GameProtocol.UserEntryResult.Builder.class);
      }

      // Construct using com.zrz.game.protobuf.GameProtocol.UserEntryResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        heroAvatar_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zrz.game.protobuf.GameProtocol.internal_static_msg_UserEntryResult_descriptor;
      }

      @java.lang.Override
      public com.zrz.game.protobuf.GameProtocol.UserEntryResult getDefaultInstanceForType() {
        return com.zrz.game.protobuf.GameProtocol.UserEntryResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.zrz.game.protobuf.GameProtocol.UserEntryResult build() {
        com.zrz.game.protobuf.GameProtocol.UserEntryResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zrz.game.protobuf.GameProtocol.UserEntryResult buildPartial() {
        com.zrz.game.protobuf.GameProtocol.UserEntryResult result = new com.zrz.game.protobuf.GameProtocol.UserEntryResult(this);
        result.userId_ = userId_;
        result.heroAvatar_ = heroAvatar_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zrz.game.protobuf.GameProtocol.UserEntryResult) {
          return mergeFrom((com.zrz.game.protobuf.GameProtocol.UserEntryResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zrz.game.protobuf.GameProtocol.UserEntryResult other) {
        if (other == com.zrz.game.protobuf.GameProtocol.UserEntryResult.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getHeroAvatar().isEmpty()) {
          heroAvatar_ = other.heroAvatar_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zrz.game.protobuf.GameProtocol.UserEntryResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zrz.game.protobuf.GameProtocol.UserEntryResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>uint32 userId = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>uint32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {

        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object heroAvatar_ = "";
      /**
       * <code>string heroAvatar = 2;</code>
       * @return The heroAvatar.
       */
      @Override
      public java.lang.String getHeroAvatar() {
        java.lang.Object ref = heroAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heroAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @return The bytes for heroAvatar.
       */
      @Override
      public com.google.protobuf.ByteString
          getHeroAvatarBytes() {
        java.lang.Object ref = heroAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @param value The heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        heroAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeroAvatar() {

        heroAvatar_ = getDefaultInstance().getHeroAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string heroAvatar = 2;</code>
       * @param value The bytes for heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        heroAvatar_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.UserEntryResult)
    }

    // @@protoc_insertion_point(class_scope:msg.UserEntryResult)
    private static final com.zrz.game.protobuf.GameProtocol.UserEntryResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zrz.game.protobuf.GameProtocol.UserEntryResult();
    }

    public static com.zrz.game.protobuf.GameProtocol.UserEntryResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEntryResult>
        PARSER = new com.google.protobuf.AbstractParser<UserEntryResult>() {
      @java.lang.Override
      public UserEntryResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEntryResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEntryResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserEntryResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zrz.game.protobuf.GameProtocol.UserEntryResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_UserEntryCmd_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_UserEntryCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_UserEntryResult_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_UserEntryResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGame.proto\022\003msg\"2\n\014UserEntryCmd\022\016\n\006use" +
      "rId\030\001 \001(\r\022\022\n\nheroAvatar\030\002 \001(\t\"5\n\017UserEnt" +
      "ryResult\022\016\n\006userId\030\001 \001(\r\022\022\n\nheroAvatar\030\002" +
      " \001(\t*4\n\007MsgCode\022\022\n\016USER_ENTRY_CMD\020\000\022\025\n\021U" +
      "SER_ENTRY_RESULT\020\001B%\n\025com.zrz.game.proto" +
      "bufB\014GameProtocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msg_UserEntryCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_UserEntryCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_UserEntryCmd_descriptor,
        new java.lang.String[] { "UserId", "HeroAvatar", });
    internal_static_msg_UserEntryResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msg_UserEntryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_UserEntryResult_descriptor,
        new java.lang.String[] { "UserId", "HeroAvatar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
